# Generated by Django 4.2.3 on 2023-09-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
